apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-app
  labels:
    app: sandbox-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-app
  template:
    metadata:
      labels:
        app: sandbox-app
        test: "1"
      annotations:
        sidecar.istio.io/inject: "true"
        instrumentation.opentelemetry.io/inject-python: "splunk/splunk-otel-collector"
        instrumentation.opentelemetry.io/container-names: "sandbox-app"
    spec:
      containers:
      - name: sandbox-app
        image: ghcr.io/s-mishina/test-otel-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_FLG
          value: "true"
        - name: API_URL
          value: "http://sandbox-app1:8081"
        - name: OTEL_LOG_LEVEL
          value: "DEBUG"
        # bash sleep
        command: ["python","main.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-app
  labels:
    app: sandbox-app
spec:
  selector:
    app: sandbox-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox-app1
  labels:
    app: sandbox-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sandbox-app1
  template:
    metadata:
      labels:
        app: sandbox-app1
        test: "2"
      annotations:
        sidecar.istio.io/inject: "true"
        instrumentation.opentelemetry.io/inject-python: "splunk/splunk-otel-collector"
        instrumentation.opentelemetry.io/container-names: "sandbox-app1"
    spec:
      containers:
      - name: sandbox-app1
        image: ghcr.io/s-mishina/test-otel-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: HTTP_FLG
          value: "false"
        - name: API_URL
          value: "dummy"
        - name: OTEL_LOG_LEVEL
          value: "DEBUG"
        command: ["python","main.py"]
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox-app1
  labels:
    app: sandbox-app1
spec:
  selector:
    app: sandbox-app1
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: test-ryu-sandbox-app
spec:
  concurrency: 0
  environmentVariables:
    ENABLE_STATS: "true"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=istio-proxy.test-ryu-sandbox-app"
  selector:
    matchLabels:
      service.istio.io/canonical-name: sandbox-app
---
apiVersion: networking.istio.io/v1beta1
kind: ProxyConfig
metadata:
  name: test-ryu-sandbox-app
spec:
  concurrency: 0
  environmentVariables:
    ENABLE_STATS: "true"
    OTEL_RESOURCE_ATTRIBUTES: "service.name=istio-proxy.test-ryu-sandbox-app2"
  selector:
    matchLabels:
      service.istio.io/canonical-name: sandbox-app1
